#!/bin/sh

filename=$1

#echo $filename

if [ -z $1 ]
then 
	sudo python3 ~/.semicolon-python/terminal.py
else

	sudo python3 ~/.semicolon-python/rm-semicolon.py $filename

	sudo python3 $filename.shadow.py

	sudo rm $filename.shadow.py

fi


