#!/bin/sh

filename=$1

#echo $filename

if [ -z $1 ]
then 
	python3
fi



python3 ~/.semicolon-python/rm-semicolon.py $filename

python3 $filename.shadow.py

rm ~/.semicolon-python/$filename.shadow.py



